# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_FSL_IMX8QM) += ultragea-imx8qm.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += ultragea-imx8qm-hdmi.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += ultragea-imx8qm-hdmi-in.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += icore-imx8xd.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += icore-imx8xq.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += smarcore-imx8xq.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += icore-imx8mm.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += icore-imx8mm-m4.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += icore-imx8mm-ctouch2-amp10.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += icoremx8m.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += icoremx8m-hdmi.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
